import {
  Accessibility,
  Activity,
  ActivitySquare,
  AirVent,
  Airplay,
  AlarmCheck,
  Album,
  AlignCenter,
  AlignCenterHorizontal,
  AlignCenterVertical,
  Aperture,
  AppWindow,
  Apple,
  Archive,
  BadgePercent,
  BarChart,
  Baseline,
  Bath,
  Bean,
  Bed,
  Bell,
  Bike,
  Binary,
  Blocks,
  Bookmark,
  Box,
  Building,
  Building2,
  Bus,
  Cake,
  CakeSlice,
  Calendar,
  Cast,
} from "lucide-react";

// WhyUs
export const fakerWhyUs = [
  {
    id: 1,
    title: "Get Close",
    desc: "Your customers have questions before they buy. Be where they are, when they need you, so they have the confidence they need to choose you over the competition. Every time.",
    image: "why-us-1.webp",
  },
  {
    id: 2,
    title: "Get Organized",
    desc: "With customer data siloed across so many tools, it’s hard to get a top-down view of the customer journey. Not anymore. You now have one place for all your customer interactions.",
    image: "why-us-2.webp",
  },
  {
    id: 3,
    title: "Get in Front",
    desc: "Easily identify FAQs and capture help center searches to create articles and shortcuts, so agents can respond faster, and customers can get help without having to make contact.",
    image: "why-us-3.webp",
  },
];

// HowItWork
export const fakerHowItWork = [
  {
    id: 1,
    title: {
      start: "Monitor customer activity in ",
      accent: "real time",
      end: "",
    },
    desc: "See which pages your visitors are on in real time, what they are searching for within your Knowledge Base and how often they visit your website. View activity across their entire journey. See clearly which team member responded to a customer last and maintain a complete conversation history.",
    image: "how-it-work-1.webp",
  },
  {
    id: 2,
    title: {
      start: "Meet customers ",
      accent: "where",
      end: " they are",
    },
    desc: "Access is the currency of the web. You need to be where your customers are, and if you’re not, your competitors will be. With tools like Live Chat, Ticketing, a Knowledge Base and video and voice add-ons, you have what you need to be there for customers when and where they need you most.",
    image: "how-it-work-2.webp",
  },
  {
    id: 3,
    title: {
      start: "",
      accent: "Collaborate",
      end: " and assign conversations",
    },
    desc: "Tag and assign conversations to members of your team and ensure the right person is responding at the right time. Seeing the entire journey alongside customer data gives you the power to respond with context and ultimately create memorable and positive customer experiences.",
    image: "how-it-work-3.webp",
  },
  {
    id: 4,
    title: {
      start: "Easily share your ",
      accent: "knowledge",
      end: "",
    },
    desc: "Streamline support with a free customizable Knowledge Base that both your team and your customers are going to love. Easily share your team’s know-how internally alongside chats, then select what to publish publicly.",
    image: "how-it-work-4.webp",
  },
  {
    id: 5,
    title: {
      start: "Have ",
      accent: "intelligent",
      end: " conversations",
    },
    desc: "Being able to respond to a conversation within the context of a customer journey, armed with shortcuts and Knowledge Base articles, makes it easy to deliver epic customer experiences.",
    image: "",
  },
];

// Features
export const fakerFeatures = [
  {
    id: 1,
    title: "45+ Languages",
    isStable: true,
    icon: Accessibility,
  },
  {
    id: 2,
    title: "JavaScript API",
    isStable: true,
    icon: ActivitySquare,
  },
  {
    id: 3,
    title: "Group Messaging",
    isStable: true,
    icon: Activity,
  },
  {
    id: 4,
    title: "Video + Voice (Add-on)",
    isStable: true,
    icon: AirVent,
  },
  {
    id: 5,
    title: "Agent > Agent Messaging",
    isStable: true,
    icon: Airplay,
  },
  {
    id: 6,
    title: "Screen Sharing",
    isStable: true,
    icon: AlarmCheck,
  },
  {
    id: 7,
    title: "Desktop Notifications",
    isStable: true,
    icon: Album,
  },
  {
    id: 8,
    title: "1880+ Emoji",
    isStable: true,
    icon: AlignCenterHorizontal,
  },
  {
    id: 9,
    title: "Geo IP Tracking",
    isStable: true,
    icon: AlignCenterVertical,
  },
  {
    id: 10,
    title: "Unlimited Agents",
    isStable: true,
    icon: AlignCenter,
  },
  {
    id: 11,
    title: "Track Sentiment",
    isStable: true,
    icon: Aperture,
  },
  {
    id: 12,
    title: "Unlimited History",
    isStable: true,
    icon: AppWindow,
  },
  {
    id: 13,
    title: "Track Engagement",
    isStable: true,
    icon: Apple,
  },
  {
    id: 14,
    title: "Detailed Reporting",
    isStable: true,
    icon: Archive,
  },
  {
    id: 15,
    title: "Ban/Unban Visitors",
    isStable: true,
    icon: BadgePercent,
  },
  {
    id: 16,
    title: "Agent Alerts",
    isStable: true,
    icon: Baseline,
  },
  {
    id: 17,
    title: "Aliases",
    isStable: true,
    icon: Bath,
  },
  {
    id: 18,
    title: "Departments",
    isStable: true,
    icon: Bed,
  },
  {
    id: 19,
    title: "File Transfer",
    isStable: true,
    icon: Bean,
  },
  {
    id: 20,
    title: "Tags",
    isStable: true,
    icon: Bell,
  },
  {
    id: 21,
    title: "Attention Bubble",
    isStable: true,
    icon: Bike,
  },
  {
    id: 22,
    title: "Domain Restriction",
    isStable: true,
    icon: Binary,
  },
  {
    id: 23,
    title: "Scheduler",
    isStable: true,
    icon: Blocks,
  },
  {
    id: 24,
    title: "Mail Notifications",
    isStable: true,
    icon: Bookmark,
  },
  {
    id: 25,
    title: "Message Filtering",
    isStable: true,
    icon: Box,
  },
  {
    id: 26,
    title: "High Load Dashboard",
    isStable: true,
    icon: Building,
  },
  {
    id: 27,
    title: "Secure Encryption",
    isStable: true,
    icon: Building2,
  },
  {
    id: 28,
    title: "Custom Tabs",
    isStable: true,
    icon: Bus,
  },
  {
    id: 29,
    title: "Message sneak-peek",
    isStable: true,
    icon: CakeSlice,
  },
  {
    id: 30,
    title: "Visitor Information",
    isStable: true,
    icon: Cake,
  },
  {
    id: 31,
    title: "In-Chat Payments",
    isStable: false,
    icon: Calendar,
  },
  {
    id: 32,
    title: "Automated Translation",
    isStable: false,
    icon: Cast,
  },
];
